[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
GtkReactive = "27996c0f-39cd-5cc1-a27a-05f136f946b6"
IDSpeak = "8c1d9be3-3b13-438f-a223-a544752cb642"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
InspectDR = "d0351b0e-4b05-5898-87b3-e2a8edfddd1d"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"
NumericIO = "6c575b1c-77cb-5640-a5dc-a54116c90507"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Reactive = "a223df75-4e93-5b7c-acf9-bdd599c0f4de"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TETechTC3625RS232 = "5c65440f-0131-45ad-8be9-cedb22662456"
